name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # リポジトリをチェックアウト
      - uses: actions/checkout@v3

      # Node.js をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 依存関係をインストール
      - name: Install dependencies
        run: npm install

      # Firebase CLI をインストール
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # サービスアカウントキーを設定
      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > sa-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/sa-key.json

      # Firebase Hosting にデプロイ
      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $PWD/sa-key.json
        run: firebase deploy --only hosting